services:
    frontend:
        build: 
            network: host
            context: .
            dockerfile: Dockerfile
        container_name: mlops-frontend
        restart: on-failure
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "http://localhost:7860"]
        #     interval: 30s          
        #     timeout: 10s           
        #     retries: 3         
        #     start_period: 10s 
        env_file:
            - .env
        ports:
            - 7860:7860
        extra_hosts:
            - "localhost:0.0.0.0"